// Top-level build file

buildscript {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.2'
        classpath 'org.lsposed.lsparanoid:gradle-plugin:0.5.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.22'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven {
            url 'https://jitpack.io'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    kotlin_version = '1.9.22'

    ktx_version = '1.9.0'

    minSdk = 21

    compileSdkVersion = 34
    compileSdk = 34

    buildToolsVersion = "34"

    targetSdkVersion = 28
    targetSdk = 28

    ndkVersion = '29.0.14033849'
    cmakeVersion = '3.22.1'

    versionName = '3.8.0'
    versionCode = 370

    useASAN = false

    blackReflection = '1.1.4'
    hiddenApiBypass = '6.1'
    xCrash = '3.1.0'
}
