name: Build AAR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install NDK
        run: sdkmanager "ndk;29.0.14033849"

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew :Bcore:assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: Bcore-aar
          path: Bcore/build/outputs/aar/*.aar
