name: Build AAR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses & Install NDK / CMake
        run: |
          yes | sdkmanager --licenses
          sdkmanager "ndk;29.0.14033849" "cmake;3.22.1"

      - name: Set Environment Variables
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/29.0.14033849" >> $GITHUB_ENV

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Clean & Build AAR
        run: ./gradlew clean :Bcore:assembleRelease --no-daemon --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bcore-aar
          path: Bcore/build/outputs/aar/*.aar
